### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by calderonth** [domodwyer/onc-rpc#1]
Hello,

Do you have an example of how to use your code? Potentially to interface with a RPC service in another language?

Cheers

**Comment by domodwyer** [comment]
Hey @calderonth 

I use this in combination with the [`BytesMut`](https://docs.rs/bytes/0.5.4/bytes/struct.BytesMut.html) type from the [`bytes`](https://crates.io/crates/bytes) crate to implement zero-copy protocol framing - in the code below, `self.read_buffer` is a `BytesMut` which is then "frozen" to an immutable `Bytes` to give to the caller:

```rust
/// read_one_msg returns a `Bytes` instance containing exactly one RPC
/// message, or awaits further data.
async fn read_one_msg(&mut self) -> Result<Bytes, ConnectionError> {
        loop {
            self.stream.read_buf(&mut self.read_buffer).await?;

            let expected_len = match expected_message_len(&self.read_buffer.clone() /* zero-copy clone */) {
                Ok(len) => len as usize,
                Err(MsgErr::IncompleteHeader) => continue,
                Err(e) => return Err(e.into()),
            };

            if expected_len > self.read_buffer.len() {
                // The buffer does not contain a full message, read more data
                continue;
            }

            // Split the buffer into a single message
            let msg_bytes = self.read_buffer.split_to(expected_len as usize);

            return Ok(msg_bytes.freeze());
        }
    }
```

`expected_message_len()` parses the header in the provided buffer, and returns an error if the buffer does not contain exactly one RPC message - this lets us await more data from a TCP stream and repeat until we have at least one message, where we split exactly one message from the buffer and return it to the caller, who parses the [`RpcMessage`] from it:

```rust
    pub async fn read(&mut self) -> Result<Request<Bytes>, ConnectionError> {
        let rpc = RpcMessage::try_from(self.read_one_msg().await?)?;

        // Read the application-specific payload
        let body = rpc.call_body().ok_or(ConnectionError::RpcNotCall)?;

        return Ok(Request::new(rpc, body));
    }
```

Here `body` contains the opaque application-specific payload, and contains the RPC protocol specific details like the message transaction ID, and the auth used, etc - be sure to *use at least 0.2.1* as I just pushed a fix for this workflow I was using locally.

Check out [the tests](https://github.com/domodwyer/onc-rpc/blob/master/src/rpc_message.rs#L428) for an example of extracting the application-specific payload - it should interface fine with a service wrote in another language so long as it faithfully implements the RPC RFC :)

If you wind up putting together an example to test with, please do open a PR to add it to the docs/example file - you make a good point, it would be very helpful!

[`RpcMessage`]: https://docs.rs/onc-rpc/0.2.1/onc_rpc/struct.RpcMessage.html

**Comment by calderonth** [comment]
Thanks I've managed to replicate some manual parsing using the example you provided and managed to get some proper unpacking working for a buffer I copied from my server's response.

Ideally, I'd like to get a pure Rust client working and I have been using the following library https://github.com/jvff/onc-rpc/ (name collision with yours btw :-) ) as it's able to generate most of the client/server boilerplate code.
However, it's using older tokio primitives and also using a serde_xdr backend that doesn't seem to work for more complex types like yours does, see https://github.com/jvff/serde-xdr/issues/5.

So I'm wondering how to bridge the gaps between those 2 implementations to get to a place where writing a client/server based a XDR the spec with a serialization layer that works end to end.

**Comment by domodwyer** [comment]
Ah that's unfortunate, I hadn't seen @jvff's repo! Sorry!

It looks like we're targeting slightly different levels of abstraction: my code is purely a codec, it handles decoding some sort of byte slice into rust types, and as such doesn't have any of the client/server code generation. The user is expected to read the input data from _somewhere_ and provide it to the codec, which is more implementation work by the user but is also more flexible as to where (or as you found, how) the data is sourced.

If you're looking for an easy client/server TCP setup and don't require the flexibility for how it works under the hood, @jvff's crate is probably the way to go 👍
