### ISSUE TITLE
How to get the payload from a reply message?

### ISSUE THREAD

**Issue by TsuITOAR** [domodwyer/onc-rpc#7]
The [specification](https://datatracker.ietf.org/doc/html/rfc5531#section-9) define the reply struct:
```
struct accepted_reply {
            opaque_auth verf;
            union switch (accept_stat stat) {
            case SUCCESS:
               opaque results[0];
               /*
                * procedure-specific results start here
                */
             case PROG_MISMATCH:
                struct {
                   unsigned int low;
                   unsigned int high;
                } mismatch_info;
             default:
                /*
                 * Void.  Cases include PROG_UNAVAIL, PROC_UNAVAIL,
                 * GARBAGE_ARGS, and SYSTEM_ERR.
                 */
                void;
             } reply_data;
         };

```
The reply message may include a procedure-specific content (payload), but it seems that there is no method getting this content in your repo, the only way to read these bytes is to access the raw buffer.   
Would you improve this or there is something I missing?

**Comment by domodwyer** [comment]
Hi @TsuITOAR 

You definitely can access the payloads - the [`AcceptedStatus`] type maps directly to the part of the specification you have quoted:

```rust
pub enum AcceptedStatus<P> 
where
    P: AsRef<[u8]>, 
 {
    Success(P),
    ProgramUnavailable,
    ProgramMismatch {
        low: u32,
        high: u32,
    },
    ProcedureUnavailable,
    GarbageArgs,
    SystemError,
}
```

If you're finding it difficult but get it working it would be awesome if you could add some example code in the repo to help others in your shoes :)

[`AcceptedStatus`]: https://docs.rs/onc-rpc/0.2.3/onc_rpc/enum.AcceptedStatus.html
